### ISSUE TITLE
Meshroom taking 12+ hours 

### ISSUE THREAD

**Issue by ashlynnholman** [nicoarellano/osarchrep#152]
Hi everyone, 

After watching the video provided, I'm having some issues in Meshroom - most nodes completed without issues in about four hours. 
It was still "meshing" at about 10pm so I let it continue to run overnight and it still seems to be stuck meshing. I tried stopping and starting but still no luck. Any one else experience this issue? My pictures are pretty big (6000 x 4000 300 dpi 11.4 MB per image) suspicious if that is potentially the issue. 
![Screenshot 2023-11-14 073744](https://github.com/nicoarellano/reposarch/assets/147101721/1db43863-0fc6-49f6-b8ec-91cfd6d56ae6)

**Comment by nicoarellano** [comment]
Hi @ashlynnholman , yes, depending on the quality and amount of the pictures and your computer graphic card it can take several hours. Mine took almost a day. I would recommend you to either be patient or to use [Metashape ](https://www.agisoft.com/downloads/installer/) (the free trial)
Let me know how it goes!
