### ISSUE TITLE
GLT not loading

### ISSUE THREAD

**Issue by Ddedee25** [nicoarellano/osarchrep#153]
Hello Nicolas, 

I'm trying to make my code work, but the error says that they don't find my files. I tried many time with different techniques and asked for help from another student, but nothing worked, my candy or Donut didn't want to show. 

What I should do? 

Thnk you in advance. 

**HTML CODE** 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../styles.css">
  <title>Sweet Party</title>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/three@0.138.0/build/three.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/three@0.138.0/examples/js/loaders/GLTFLoader.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/three@0.138.0/examples/js/controls/OrbitControls.js"></script>
  <script type="module" src="./main.js" defer></script>
  <canvas id="three-canvas"></canvas>
</body>
</html>

**JAVACODE**

const scene = new THREE.Scene();

const size = {
  width: window.innerWidth,
  height: window.innerHeight,
};

const aspect = size.width / size.height;
const camera = new THREE.PerspectiveCamera(75, aspect, 0.1, 1000);

//Sets up the renderer, fetching the canvas of the HTML
const threeCanvas = document.getElementById("three-canvas");
const renderer = new THREE.WebGLRenderer({
  canvas: threeCanvas,
  alpha: true,
});

renderer.setSize(size.width, size.height);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
document.body.appendChild(renderer.domElement);

//Creates grids and axes in the scene
const grid = new THREE.GridHelper(50, 30);
scene.add(grid);

const axes = new THREE.AxesHelper();
axes.material.depthTest = false;
axes.renderOrder = 1;
scene.add(axes);

const geometry = new THREE.BoxGeometry(1, 1, 1);

const yellowMaterial = new THREE.MeshLambertMaterial({ color: 0xffff00 });
const blueMaterial = new THREE.MeshLambertMaterial({ color: 0x0000ff });
const redMaterial = new THREE.MeshLambertMaterial({ color: 0xff0000 });
const greenMaterial = new THREE.MeshLambertMaterial({ color: 0x00ff00 });

const yellowCube = new THREE.Mesh(geometry, yellowMaterial);
const blueCube = new THREE.Mesh(geometry, blueMaterial);
const redCube = new THREE.Mesh(geometry, redMaterial);
const greenCube = new THREE.Mesh(geometry, greenMaterial);

yellowCube.position.z = -3;
blueCube.position.x = -3;
redCube.position.x = 3;
greenCube.position.z = 3;

scene.add(yellowCube);
scene.add(blueCube);
scene.add(redCube);
scene.add(greenCube);

const gltfLoader = new THREE.GLTFLoader();

let mesh;
 
function loadGLB(path,scale,x,z){
  gltfLoader.load(
         path,
            function (gltf) {
              mesh = gltf.scene;
              mesh.scale.x = scale;
              mesh.scale.y = scale;
              mesh.scale.z = scale;
                mesh.position.x = x
                mesh.position.z = z
          scene.add(mesh);

        },
          undefined,
          function (error) {
          console.error(error);
          }
  );
}

loadGLB("./models/wDonut2.glb");

camera.position.z = 7;
camera.position.x = 4;
camera.position.y = 6;

const controls = new THREE.OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;

//Creates the lights of the scene
const lightColor = 0xffffff;

const ambientLight = new THREE.AmbientLight(lightColor, 0.5);
scene.add(ambientLight);

const directionalLight = new THREE.DirectionalLight(lightColor, 1);
directionalLight.position.set(5, 10, 5);
directionalLight.target.position.set(0, 3, 0);
scene.add(directionalLight);
scene.add(directionalLight.target);

function animate() {
  requestAnimationFrame(animate);

  if (mesh) mesh.rotation.y += 0.01;

  yellowCube.rotation.x += 0.01;
  yellowCube.rotation.y += 0.01;

  blueCube.rotation.x += 0.02;
  blueCube.rotation.y -= 0.01;

  redCube.rotation.x -= 0.01;
  redCube.rotation.y -= 0.02;

  greenCube.rotation.x += 0.02;
  greenCube.rotation.y -= 0.01;

  renderer.render(scene, camera);
}

animate();

//Adjust the viewport to the size of the browser
window.addEventListener("resize", () => {
  size.width = window.innerWidth;
  size.height = window.innerHeight;
  camera.aspect = size.width / size.height;
  camera.updateProjectionMatrix();
  renderer.setSize(size.width, size.height);
});

**Comment by nicoarellano** [comment]
Hi Andree-Ann,

Please make sure `./models/wDonut2.glb` is the right location. You can ask Jeremy about that.
If you are running it locally maybe, but if you are running it on my page, it may be something like this:
"/arcn5005/f2023/students/andreeannlangevin/models/wDonut2.glb"

Also, make sure your file is called exactly like that and it is contain in that folder.

Please push your code so I can see it easily

**Comment by Ddedee25** [comment]
Hello again Nicolas, 
I'm trying to commit my code from visual studio to Github, and still turning after 10 minutes, I don't know if it's normal. 

![Committing](https://github.com/nicoarellano/reposarch/assets/144391550/74ce9cfe-282f-4491-990e-6670aac1e814)

**Comment by nicoarellano** [comment]
You need to add a message. It is mandatory.

Close VS code and try that. It should work.

Please let me know otherwise

**Comment by Ddedee25** [comment]
Ok, I just closed it and committed again with a message, seems to work for a minute but now I got this.... 
![image](https://github.com/nicoarellano/reposarch/assets/144391550/92defb58-f281-46d9-b050-d3cecf0755f1)

**Comment by nicoarellano** [comment]
Try syncing your remote branch on GitHub and then on the VS terminal do a git pull.
Then try to commit again.

Let me know how it goes

**Comment by Ddedee25** [comment]
![image](https://github.com/nicoarellano/reposarch/assets/144391550/423e06a2-2a20-4d5b-89fe-54f00340b4c2)
 
![image](https://github.com/nicoarellano/reposarch/assets/144391550/60bb9cba-4d59-4f6b-868f-1cf3e3a4204d)

![image](https://github.com/nicoarellano/reposarch/assets/144391550/c8247420-754e-4fbf-8516-a1c7c94aa096)

**Comment by Ddedee25** [comment]
Hello again Nicolas, 
thank you for your help by the way.  
Still not working, I screenshot every step to show you. Daphnee tried to help me all day and she didn't get the problem either.

**Comment by Ddedee25** [comment]
I think the pull request finally works.

**Comment by nicoarellano** [comment]
I am happy to hear!
Once again thanks a lot @daphnestams !!
