### ISSUE TITLE
Having difficulty to sync my code and push the commit

### ISSUE THREAD

**Issue by Mucheeeeen** [nicoarellano/osarchrep#172]
Morning Nico.

I am having hard time to sync my code and push commit

my visual studio code showing this once i hit the sync button

![image](https://github.com/nicoarellano/reposarch/assets/144391511/88db6498-3ee5-4365-aa6e-f7e37519cb06)

Also My github desktop showing this when I push commit to origin repository.

![image](https://github.com/nicoarellano/reposarch/assets/144391511/ffd41a52-498c-4beb-8024-30f898ddfcd1)

any solutions to these issues?

**Comment by Mucheeeeen** [comment]
> git push origin dev:dev
error: RPC failed; HTTP 408 curl 22 The requested URL returned error: 408
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

Visual Studio Code showing this error when I wanna sync my changes

**Comment by nicoarellano** [comment]
Hi Muchen, Make sure you always type a message before committing:
![image](https://github.com/nicoarellano/reposarch/assets/95719187/00299962-84f5-4643-8676-2e568bd39ddb)

**Comment by Mucheeeeen** [comment]
![image](https://github.com/nicoarellano/reposarch/assets/144391511/8db53d5d-69df-4f72-b4ae-01ef367c258c)

I've tried to type message several times but I still got same results

**Comment by Mucheeeeen** [comment]
I re-cloned the entire repository and finally it get rid of the error. Thank you, Nico

**Comment by nicoarellano** [comment]
Super happy to hear that.
