### ISSUE TITLE
Pull

### ISSUE THREAD

**Issue by benbsegal** [nicoarellano/osarchrep#395]
Hey Nico, 
I want to make sure my final has been committed. I submitted last night but I haven’t received a vercel confirmation so I’m worried it didn’t commit

**Comment by nicoarellano** [comment]
Hi Ben, 
Yes, I have received everything. The only thing I never got was your mesh. You were not able to export it as GLTF?

**Comment by benbsegal** [comment]
No It only allowed me to export as a USDZ file or to pay a yearly subscription to be able to export as a a GLTF

**Comment by nicoarellano** [comment]
Not sure if it works, but try:
https://products.aspose.app/3d/conversion/usdz-to-gltf
Otherwise you can always google : USDZ to GLTF converter. 
Or try with blender

**Comment by benbsegal** [comment]
I committed a GLTF file I signed up for a week free trial so it should be uploaded now

**Comment by nicoarellano** [comment]
That is excellent, let me see.

**Comment by nicoarellano** [comment]
OK, so it looks like you have successfully uploaded the mesh, however, you have not added it to your scene, so it will not show up.
These are the meshes you have loaded:
```// Load GLB models and add them to the scene
loadGLB("./Models/astronaut.glb", 0.5, 0, 0, 0);
loadGLB("./Models/need_some_space.glb", 200, -285, -285, 300);
loadGLB("./Models/space_shuttle.glb", 0.5, 10, 0, -10);
loadGLB("./Models/space_rocks.glb", 10, 0, 0, 15);
```
Let me know if you have questions

**Comment by nicoarellano** [comment]
I received it, and I can see it. I think it looks great, so please add it to your scene. It is going to look awesome floating on the space
![image](https://github.com/nicoarellano/reposarch/assets/95719187/87ede858-2b4d-431a-a74e-99c3771b3162)
