### ISSUE TITLE
FInal

### ISSUE THREAD

**Issue by EvanJMartyn** [nicoarellano/osarchrep#404]
Hi Nico,

I sent an email a few days ago, my flex box is not quite working for my site. However I was successful in posting it to my own git. 
The link is as follows:

https://evanjmartyn.github.io/Final-Project-ARCN-5005/

Let me know if you have any suggestions on how to solve that issue placing my glb and map next to each other?

Thanks,
Evan

**Comment by nicoarellano** [comment]
Hi Evan, that looks good. 
Good work. 
Happy holidays.
Have a restful break.

Best,

Nico
