### ISSUE TITLE
Meshroom Image Import Error: Corrupt Image

### ISSUE THREAD

**Issue by farisitum** [nicoarellano/osarchrep#57]
I am trying to move my photographs (taken on my iPhone) to Meshroom, but keep running into the same error: 'You probably have a corrupted image within the images that you are trying to import'. 
Not sure how to get around the issue, have tried re-uploading my images but the error remains.
Please help

![Screenshot 2023-09-16 120421](https://github.com/nicoarellano/reposarch/assets/144391398/1815836d-468a-40b2-a03d-bd4495d704e0)

**Comment by farisitum** [comment]
Issue solved: Reuploaded images through USB rather than Dropbox

**Comment by farisitum** [comment]
Error during DepthMap: "This program needs a CUDA-Enabled GPU (with at least compute capability 2.0)."

**Comment by nicoarellano** [comment]
Good job Faris! I am glad it got resolved quickly
